site_name: My Docs

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - navigation.indexes
    - navigation.top
    - navigation.tabs
    - navigation.tracking
    - content.code.annotate
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: JetBrains Mono

nav:
  - Home:
    - Hotpot: index.md
    - Guide: guide.md
  - About:
    - Welcome: about.md

plugins:
  - search
  - git-revision-date-localized:
      type: timeago
        
markdown_extensions:
  - admonition
  - toc:
      permalink: true

extra_css:
  - styles/extra.css
