site_name: My Docs

theme:
  name: material
  features:
    # navigation
    - navigation.sections
    # - navigation.expand
    - navigation.indexes
    - navigation.footer
    - navigation.top
    - navigation.tabs
    - navigation.tracking
    # content
    - content.code.annotate
    - toc.follow
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home:
    - Hotpot: index.md
    - Guide: guide.md
  - About:
    - Welcome: about.md

plugins:
  - search
  - git-revision-date-localized:
      type: timeago
  - minify:
      minify_html: true
      
markdown_extensions:
  - admonition
  - toc:
      permalink: true

extra_css:
  - styles/extra.css
