site_name: My Docs

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - content.code.annotate
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono

nav:
  - Home:
      - index.md
      - guide.md
  - About:
      - about.md

docs_dir: docs

markdown_extensions:
  - admonition
  - toc:
      permalink: true

plugins:
  - search
  - git-revision-date-localized:
      type: timeago

extra_css:
  - styles/extra.css
