site_name: My Docs

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - content.code.annotate
  palette:
    - scheme: default
      primary: white
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: assets/logo.png  # optional custom logo
  favicon: assets/favicon.ico  # optional

nav:
  - Home: index.md
  - Guide: guide.md
  - About: about.md

docs_dir: docs

markdown_extensions:
  - admonition
  - toc:
      permalink: true

plugins:
  - search
