export default {
  aboutSidebar: [{ type: 'autogenerated', dirName: 'about' }],
};

// =============================================
// Use the following for blogless single sidebar
// =============================================

// export default {
//   docSidebar: [{ type: 'autogenerated', dirName: '.' }],
// };